# Generated by Django 6.1 on 2026-08-19 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_tenantuser_role'),
        ('customers', '0003_remove_tenant_on_trial_remove_tenant_paid_until'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tenantuser',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='tenantuser',
            constraint=models.UniqueConstraint(fields=('tenant', 'user'), name='unique_tenant_user'),
        ),
    ]
