# Generated by Django 6.1 on 2026-08-18 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('customers', '0001_initial'),
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Client',
            new_name='Tenant',
        ),
    ]
