# Generated by Django 6.1 on 2026-09-09 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0003_remove_tenant_on_trial_remove_tenant_paid_until'),
    ]

    operations = [
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('integration_type', models.CharField(choices=[('wazuh', 'Wazuh'), ('misp', 'MISP'), ('openvas', 'OpenVAS'), ('suricata', 'Suricata'), ('zeek', 'Zeek'), ('virustotal', 'VirusTotal'), ('custom', 'Custom')], max_length=50)),
                ('base_url', models.URLField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('disabled', 'Disabled'), ('error', 'Error')], default='pending', max_length=30)),
                ('verify_ssl', models.BooleanField(default=True)),
                ('enabled', models.BooleanField(default=True)),
                ('configuration', models.JSONField(blank=True, default=dict)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrations', to='customers.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('tenant', 'integration_type')},
            },
        ),
        migrations.CreateModel(
            name='IntegrationCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=255)),
                ('secret', models.TextField(blank=True)),
                ('token', models.TextField(blank=True)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('integration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credential', to='intergration.integration')),
            ],
        ),
    ]
