# Generated by Django 6.1 on 2026-09-09 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intergration', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='integration',
            unique_together={('name', 'integration_type')},
        ),
        migrations.RemoveField(
            model_name='integration',
            name='tenant',
        ),
    ]
