# Generated by Django 6.1 on 2026-09-09 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intergration', '0002_alter_integration_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='integrationcredential',
            name='secret',
        ),
        migrations.RemoveField(
            model_name='integrationcredential',
            name='token',
        ),
        migrations.AddField(
            model_name='integration',
            name='port',
            field=models.PositiveIntegerField(default=55000),
        ),
        migrations.AddField(
            model_name='integrationcredential',
            name='password',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
