# Generated by Django 6.1 on 2026-09-09 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_remove_tenant_on_trial_remove_tenant_paid_until'),
        ('intergration', '0003_remove_integrationcredential_secret_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('integration_type', models.CharField(choices=[('wazuh', 'Wazuh'), ('misp', 'MISP'), ('openvas', 'OpenVAS'), ('virustotal', 'VirusTotal')], max_length=50, unique=True)),
                ('base_url', models.URLField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('disabled', 'Disabled'), ('error', 'Error')], default='pending', max_length=30)),
                ('verify_ssl', models.BooleanField(default=False)),
                ('enabled', models.BooleanField(default=True)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='integrationcredential',
            name='integration',
        ),
        migrations.CreateModel(
            name='PlatformIntegrationCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=255)),
                ('secret', models.TextField(blank=True)),
                ('token', models.TextField(blank=True)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('integration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credential', to='intergration.platformintegration')),
            ],
        ),
        migrations.CreateModel(
            name='TenantWazuhGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(help_text='Wazuh group name for this tenant e.g. tenant_acme', max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wazuh_group', to='customers.tenant')),
            ],
        ),
        migrations.DeleteModel(
            name='Integration',
        ),
        migrations.DeleteModel(
            name='IntegrationCredential',
        ),
    ]
