# Generated by Django 6.1 on 2026-09-09 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intergration', '0004_platformintegration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platformintegrationcredential',
            name='secret',
        ),
        migrations.AddField(
            model_name='platformintegrationcredential',
            name='password',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
