# Generated by Django 6.1 on 2026-09-09 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intergration', '0005_remove_platformintegrationcredential_secret_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformintegration',
            name='port',
            field=models.PositiveIntegerField(blank=True, default=55000, null=True),
        ),
    ]
